services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=taskmanagement'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=taskmanagement'
    ports:
      - '5432:5432'
